CREATE TABLE IF NOT EXISTS ShippingRateCache (
    id INT PRIMARY KEY,
    senderPostcode VARCHAR(255) NOT NULL,
    receiverPostcode VARCHAR(255) NOT NULL,
    weight DOUBLE PRECISION NOT NULL,
    length DOUBLE PRECISION NOT NULL,
    width DOUBLE PRECISION NOT NULL,
    height DOUBLE PRECISION NOT NULL,
    provider VARCHAR(255) NOT NULL,
    rate DOUBLE PRECISION NOT NULL,
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);